### ISSUE TITLE
Bug: uptime unkown

### ISSUE THREAD

**Issue by evilae** [r3tr0ananas/pengufetch#2]
![image](https://github.com/user-attachments/assets/71ba9196-209e-4c57-9d17-a3522c8a7d01)

## *Who* is the bug affecting?

the bug is affecting me and probably other nixOS users

## *What* is affected by this bug?

uptime function

## *When* does this occur?

When I run the command

## *Where* on the platform does it happen?

nixOS

## *How* do we replicate the issue?

* Download the [binary](https://github.com/r3tr0ananas/pengufetch/releases/download/v1.0.0/pengufetch_Linux_x86_64.tar.gz)
* `tar -xzvf  pengufetch_Linux_x86_64.tar.gz`
* chmod +x pengufetch
* ./pengufetch

## Expected behavior (i.e. solution)

show me the uptime 

## Other Comments

**Comment by ananasmoe** [comment]
5db4ca6dcd03090d64ab2ff7d4497b4b5a046499
